/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pet } from './Pet'

export const statusEnum = {
    available: "available",
    pending: "pending",
    sold: "sold"
} as const;

export type StatusEnumKey = (typeof statusEnum)[keyof typeof statusEnum];

export type LoginAndReadPetOutputs = {
    token: string;
    pet: Pet;
    status: StatusEnumKey;
};
