/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from '../../zod.ts'
import { orderSchema } from './orderSchema'

export const getOrderByIdPathOrderIdSchema = z.coerce.bigint().describe('ID of order that needs to be fetched')

export type GetOrderByIdPathOrderIdSchemaType = z.infer<typeof getOrderByIdPathOrderIdSchema>

export const getOrderByIdStatus200SchemaJson = orderSchema

export type GetOrderByIdStatus200SchemaJsonType = z.infer<typeof getOrderByIdStatus200SchemaJson>

export const getOrderByIdStatus200SchemaXml = orderSchema

export type GetOrderByIdStatus200SchemaXmlType = z.infer<typeof getOrderByIdStatus200SchemaXml>

export const getOrderByIdStatus200Schema = z.union([getOrderByIdStatus200SchemaJson, getOrderByIdStatus200SchemaXml])

export type GetOrderByIdStatus200SchemaType = z.infer<typeof getOrderByIdStatus200Schema>

export const getOrderByIdStatus400Schema = z.unknown()

export type GetOrderByIdStatus400SchemaType = z.infer<typeof getOrderByIdStatus400Schema>

export const getOrderByIdStatus404Schema = z.unknown()

export type GetOrderByIdStatus404SchemaType = z.infer<typeof getOrderByIdStatus404Schema>

export const getOrderByIdResponseSchema = getOrderByIdStatus200Schema

export type GetOrderByIdResponseSchemaType = z.infer<typeof getOrderByIdResponseSchema>

export const getOrderByIdErrorSchema = z.union([getOrderByIdStatus400Schema, getOrderByIdStatus404Schema])

export type GetOrderByIdErrorSchemaType = z.infer<typeof getOrderByIdErrorSchema>

export const getOrderByIdPathSchema = z.object({
  orderId: z.coerce.bigint().describe('ID of order that needs to be fetched'),
})

export type GetOrderByIdPathSchemaType = z.infer<typeof getOrderByIdPathSchema>

export const getOrderByIdOptionsSchema = z.object({
  body: z.never().optional(),
  path: getOrderByIdPathSchema,
  query: z.never().optional(),
  headers: z.never().optional(),
})

export type GetOrderByIdOptionsSchemaType = z.infer<typeof getOrderByIdOptionsSchema>

export const getOrderByIdResponsesSchema = z.object({
  '200': z.union([
    z.object({
      contentType: z.enum(['application/json']),
      data: getOrderByIdStatus200SchemaJson,
    }),
    z.object({
      contentType: z.enum(['application/xml']),
      data: getOrderByIdStatus200SchemaXml,
    }),
  ]),
  '400': getOrderByIdStatus400Schema,
  '404': getOrderByIdStatus404Schema,
})

export type GetOrderByIdResponsesSchemaType = z.infer<typeof getOrderByIdResponsesSchema>
