/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import { slotSchema } from './slotSchema'

export const bookRefSlotStatus201Schema = slotSchema

export const bookRefSlotResponseSchema = bookRefSlotStatus201Schema

export const bookRefSlotBodySchema = slotSchema
